using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;

namespace AutopilotCommon
{
    public class ParameterHandler : IEnumerable<Parameter>
    {
        private bool saveEnabled = false;
        private string saveFile;
        private string defaultFile;
        //List backing isn't ideal but we need indexes...
        private List<Parameter> parameters = new List<Parameter>();
        public ParameterHandler(string dir, string saveFile, string defaultFile)
        {

            this.saveFile = dir + saveFile;
            this.defaultFile = dir + defaultFile;
            Console.WriteLine($"Paramters:\t{dir + saveFile}");
            Console.WriteLine($"defaults:\t{dir + defaultFile}");
            SetDefault(saveFile, defaultFile);
            Load(saveFile);
        }

        public void Load(string file)
        {
            lock (parameters)
            {
                int beforeTotal = parameters.Count;
                int afterTotal = 0;
                if (File.Exists(file))
                {
                    using (StreamReader sr = new StreamReader(file))
                    {

                        string currentLine = null;
                        while ((currentLine = sr.ReadLine()) != null)
                        {
                            afterTotal++;
                            int indexOfColon = currentLine.IndexOf(":");
                            int indexOfEquals = currentLine.IndexOf("=");
                            string typePart = currentLine.Substring(0, indexOfColon);
                            string idPart = currentLine.Substring(indexOfColon + 1, indexOfEquals - indexOfColon - 1);
                            string valuePart = currentLine.Substring(indexOfEquals + 1);
                            float valueFloat = float.Parse(valuePart);
                            MAVLink.MAV_PARAM_TYPE paramType = (MAVLink.MAV_PARAM_TYPE)Enum.Parse(typeof(MAVLink.MAV_PARAM_TYPE), typePart);
                            Console.WriteLine($"{idPart} , {valueFloat} , {paramType}");
                            SetParameter(idPart, valueFloat, paramType);
                        }
                    }
                }
                //Save new/missing parameters.
                saveEnabled = true;
                if (beforeTotal != afterTotal)
                {
                    Save(saveFile);
                }
            }
        }

        public void Save(string file)
        {
            lock (parameters)
            {
                using (StreamWriter sw = new StreamWriter(file))
                {
                    foreach (Parameter p in parameters)
                    {
                        sw.WriteLine($"{p.type}:{p.id}={p.value}");
                    }
                }
            }
        }

        public Parameter GetParameter(string id)
        {
            foreach (Parameter p in parameters)
            {
                if (p.id == id)
                {
                    Console.WriteLine($"{p} , {p.id}");
                    return p;
                }
            }
            return null;
        }

        public int SetParameter(string id, float value, MAVLink.MAV_PARAM_TYPE type)
        {
            lock (parameters)
            {
                Parameter p = GetParameter(id);
                if (p != null)
                {
                    p.value = value;
                    p.type = type;
                }
                else
                {
                    p = new Parameter(id, value, type);
                    parameters.Add(p);
                }
                if (saveEnabled)
                {
                    Save(defaultFile);
                }
                return parameters.IndexOf(p);
            }
        }

        public int GetCount()
        {
            return parameters.Count;
        }

        public int IndexOf(Parameter p)
        {
            if (parameters.Contains(p))
            {
                return parameters.IndexOf(p);
            }
            return -1;
        }

        public IEnumerator<Parameter> GetEnumerator()
        {
            return parameters.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void SetDefault(string fileP,string fileD)
        {
            if (!File.Exists(fileP))
            {
                if (File.Exists(fileD))
                {
                    using (StreamReader df = new StreamReader(fileD))
                    {
                        string currentLine = null;
                        while ((currentLine = df.ReadLine()) != null)
                        {
                            Save(fileP);
                        }

                    }
                }
                else
                {
                    SetParameter("RCMAP_ROLL", 1f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RCMAP_PITCH", 2f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RCMAP_YAW", 4f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RCMAP_THROTTLE", 3f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GLIDE_SLOPE_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GLIDE_SLOPE_THR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("STICK_MIXING", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_THR_MINSPD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_THR_MINACC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_THR_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_TDRAG_ELEV", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_TDRAG_SPD1", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_ROTATE_SPD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_THR_SLEW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_PLIM_SEC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_FLAP_PCNT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LEVEL_ROLL_LIMIT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("USE_REV_THRUST", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ALT_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("WP_RADIUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("WP_MAX_RADIUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("WP_LOITER_RAD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RTL_RADIUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("STALL_PREVENTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_FBW_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_FBW_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FBWB_ELEV_REV", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TERRAIN_FOLLOW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TERRAIN_LOOKAHD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FBWB_CLIMB_RATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_THR_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_SLEWRATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLAP_SLEWRATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_SUPP_MAN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_PASS_STAB", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_FAILSAFE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THR_FS_VALUE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TRIM_THROTTLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("THROTTLE_NUDGE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FS_SHORT_ACTN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FS_SHORT_TIMEOUT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FS_LONG_ACTN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FS_LONG_TIMEOUT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FS_GCS_ENABL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE_CH:", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE1", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE2", 5f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE3", 7f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE4", 15f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE5", 11f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLTMODE6", 21f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INITIAL_MODE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LIM_ROLL_CD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LIM_PITCH_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LIM_PITCH_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ACRO_ROLL_RATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ACRO_PITCH_RATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ACRO_LOCKING", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GROUND_STEER_ALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GROUND_STEER_DPS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TRIM_AUTO", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MIXING_GAIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RUDDER_ONLY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MIXING_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("DSPOILR_RUD_RATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("SYS_NUM_RESETS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LOG_BITMASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TRIM_ARSPD_CM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("SCALING_SPEED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MIN_GNDSPD_CM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TRIM_PITCH_CD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ALT_HOLD_RTL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ALT_HOLD_FBWCM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLAP_1_PERCNT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLAP_1_SPEED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLAP_2_PERCNT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLAP_2_SPEED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("OVERRIDE_CHAN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RTL_AUTOLAND", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CRASH_ACC_THRESH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CRASH_DETECT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RNGFND_LANDING", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("SYSID_ENFORCE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RUDD_DT_GAIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MANUAL_RCMASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("HOME_RESET_ALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLIGHT_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_ACCEL_CNT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("DSPOILER_CROW_W1", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("DSPOILER_CROW_W2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TKOFF_TIMEOUT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("DSPOILER_OPTS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("DSPOILER_AILMTCH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FWD_BAT_VOLT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FWD_BAT_VOLT_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FWD_BAT_IDX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FS_EKF_THRESH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RTL_CLIMB_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MAN_EXPO_ROLL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MAN_EXPO_PITCH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MAN_EXPO_RUDDER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ONESHOT_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_LIST_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_LIST_RADIUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_ICAO_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_EMIT_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_LEN_WIDTH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_OFFSET_LAT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_OFFSET_LON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_RF_SELECT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_SQUAWK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_RF_CAPABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_LIST_ALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_ICAO_SPECL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ADSB_LOG", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_MAN_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_HB_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_WP_COMMS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_WP_GPS_LOSS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_TERMINATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_TERM_ACTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_TERM_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_AMSL_LIMIT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_AMSL_ERR_GPS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_QNH_PRESSURE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_MAX_GPS_LOSS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_MAX_COM_LOSS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_GEOFENCE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_RC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_RC_MAN_ONLY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_DUAL_LOSS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AFS_RC_FAIL_TIME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_GPS_GAIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_GPS_USE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_YAW_P", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_RP_P", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_WIND_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_TRIM_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_TRIM_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_ORIENTATION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_COMP_BETA", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_GPS_MINSATS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_EKF_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_CUSTOM_ROLL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_CUSTOM_PIT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AHRS_CUSTOM_YAW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARMING_REQUIRE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARMING_ACCTHRESH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARMING_RUDDER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARMING_MIS_ITEMS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARMING_CHECK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_DEVID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_USE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_RATIO", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_AUTOCAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT16);
                    SetParameter("ARSPD_TUBE_ORDER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_SKIP_CAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_PSI_RANGE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_PRIMARY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_WIND_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ARSPD_WIND_WARN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_F_ACTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_W_ACTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_F_RCVRY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_OBS_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_W_TIME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_F_TIME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_W_DIST_XY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_F_DIST_XY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_W_DIST_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_F_DIST_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("AVD_F_ALT_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_GND_PRESS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_GND_TEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_ALT_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_PRIMARY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_EXT_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_SPEC_GRAV", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_GND_PRESS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_GND_PRESS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_FLTR_RNG", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO_PROBE_EXT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_DEVID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_DEVID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_DEVID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_WCF_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_WCF_FWD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_WCF_BCK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_WCF_RGT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO1_WCF_LFT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_WCF_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_WCF_FWD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_WCF_BCK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_WCF_RGT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO2_WCF_LFT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_WCF_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_WCF_FWD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_WCF_BCK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_WCF_RGT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BARO3_WCF_LFT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT3_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT4_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT5_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT6_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT7_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT8_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT2_MONITOR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_CAPACITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_WATT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_SERIAL_NUM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_LOW_TIMER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_FS_VOLTSRC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_LOW_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_LOW_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_CRT_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_CRT_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_FS_LOW_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_FS_CRT_ACT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_ARM_VOLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_ARM_MAH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_VOLT_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_CURR_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_VOLT_MULT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_AMP_PERVLT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_AMP_OFFSET", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_I2C_BUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("BATT9_I2C_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_TRIGG_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_DURATION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_SERVO_ON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_SERVO_OFF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_TRIGG_DIST", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RELAY_ON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_MIN_INTERVAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_MAX_ROLL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_FEEDBACK_PIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_FEEDBACK_POL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_AUTO_ONLY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RC_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RC_FEATURES", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RC_BT_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RC_BTN_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RC_MDE_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CAM_RC_CONTROL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MNT_RC_IN_ROLL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MNT_RC_IN_PAN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MNT_RC_IN_TILT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_ENABLED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_SERVO_ON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_SERVO_OFF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_ALT_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_DELAY_MS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_CRT_SINK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("CHUTE_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_LEARN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_USE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_AUTODEC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOTCT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ORIENT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_EXTERNAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFS3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_MOT3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID3", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_USE2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ORIENT2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_EXTERN2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_USE3", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ORIENT3", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_EXTERN3", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DIA3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ODI3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_CAL_FIT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OFFS_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_TYPEMASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_FLTR_RNG", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_AUTO_ROT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PRIO1_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PRIO2_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PRIO3_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_SCALE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_SCALE2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_SCALE3", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID4", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID5", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID6", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID7", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_DEV_ID8", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_CUS_ROLL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_CUS_PIT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_CUS_YAW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT_EN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT_EXP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT1_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT1_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT1_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT4_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT4_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("COMPASS_PMOT4_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EAHRS_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EAHRS_RATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EFI_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EFI_COEF1", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EFI_COEF2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GPS_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_VELNE_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_VELD_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_VEL_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_POSNE_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_POS_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GLITCH_RAD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_ALT_SOURCE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_ALT_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_HGT_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_HGT_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAG_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAG_CAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAG_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_EAS_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_EAS_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_RNG_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_RNG_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAX_FLOW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_FLOW_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_FLOW_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_FLOW_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GYRO_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_ACC_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GBIAS_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GSCL_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_ABIAS_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_WIND_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_WIND_PSCALE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GPS_CHECK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_IMU_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_CHECK_SCALE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_NOAID_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_YAW_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_YAW_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_TAU_OUTPUT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAGE_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAGB_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_RNG_USE_HGT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_TERR_GRAD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_BCN_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_BCN_I_GTE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_BCN_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_RNG_USE_SPD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAG_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_OGN_HGT_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_FLOW_USE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_MAG_EF_LIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_HRT_FILT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GSF_RUN_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GSF_USE_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK2_GSF_RST_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_VELNE_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_VELD_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_VEL_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_POSNE_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_POS_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GLITCH_RAD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_ALT_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_HGT_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_HGT_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAG_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAG_CAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAG_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_EAS_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_EAS_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_RNG_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_RNG_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAX_FLOW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_FLOW_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_FLOW_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_FLOW_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GYRO_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_ACC_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GBIAS_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_ABIAS_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_WIND_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_WIND_PSCALE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GPS_CHECK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_IMU_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_CHECK_SCALE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_NOAID_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_BETA_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_YAW_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_YAW_I_GATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_TAU_OUTPUT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAGE_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAGB_P_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_RNG_USE_HGT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_TERR_GRAD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_BCN_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_BCN_I_GTE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_BCN_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_RNG_USE_SPD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_ACC_BIAS_LIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAG_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_OGN_HGT_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_VIS_VERR_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_VIS_VERR_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_WENC_VERR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_FLOW_USE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_HRT_FILT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_MAG_EF_LIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GSF_RUN_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GSF_USE_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GSF_RST_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_ERR_THRESH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_AFFINITY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_DRAG_BCOEF_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_DRAG_BCOEF_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_DRAG_M_NSE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_DRAG_MCOEF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_OGNM_TEST_SF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_GND_EFF_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_PRIMARY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC1_POSXY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC1_VELXY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC1_POSZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC1_VELZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC1_YAW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC2_POSXY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC2_VELXY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC2_POSZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC2_VELZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC2_YAW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC3_POSXY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC3_VELXY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC3_POSZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC3_VELZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC3_YAW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("EK3_SRC_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_ACTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_ALT_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_RADIUS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_MARGIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_TOTAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_ALT_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_RET_RALLY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_RET_ALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FENCE_AUTOENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_MINHZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_MAXHZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_SAMPLE_MODE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_WINDOW_SIZE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_WINDOW_OLAP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_FREQ_HOVER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_THR_REF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_SNR_REF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_ATT_REF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_BW_HOVER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_HMNC_FIT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FFT_HMNC_PEAK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_FXSCALER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_FYSCALER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_ORIENT_YAW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_POS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_POS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_POS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("FLOW_ADDR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GEN_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_TYPE2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_NAVFILTER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_AUTO_SWITCH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MIN_DGPS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_SBAS_MODE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MIN_ELEV", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_SBP_LOGMASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_RAW_DATA", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_GNSS_MODE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_SAVE_CFG", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_GNSS_MODE2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_AUTO_CONFIG", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_RATE_MS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_RATE_MS2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_POS1_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_POS1_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_POS1_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_POS2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_POS2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_POS2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_DELAY_MS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_DELAY_MS2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_BLEND_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_BLEND_TC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_DRV_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_COM_PORT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_COM_PORT2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_PRIMARY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_CAN_NODEID1", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_CAN_NODEID2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS1_CAN_OVRIDE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS2_CAN_OVRIDE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB1_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB1_OFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB1_OFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB1_OFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB2_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB2_OFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB2_OFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GPS_MB2_OFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_GRAB", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_RELEASE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_NEUTRAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_REGRAB", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GRIP_UAVCAN_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_P", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_I", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_D", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_FF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_IMAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_FLTT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_FLTE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_FLTD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("GUIDED_SMAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_START_CHAN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_STARTER_TIME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_START_DELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_RPM_THRESH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_PWM_IGN_ON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_PWM_IGN_OFF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_PWM_STRT_ON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_PWM_STRT_OFF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_RPM_CHAN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_START_PCT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_IDLE_PCT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_IDLE_RPM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_IDLE_DB", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_IDLE_SLEW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("ICE_STARTCHN_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYROFFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYROFFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYROFFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR2OFFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR2OFFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR2OFFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR3OFFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR3OFFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR3OFFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCSCAL_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCSCAL_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCSCAL_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCOFFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCOFFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCOFFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2SCAL_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2SCAL_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2SCAL_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2OFFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2OFFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2OFFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3SCAL_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3SCAL_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3SCAL_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3OFFS_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3OFFS_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3OFFS_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYRO_FILTER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACCEL_FILTER", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_USE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_USE2", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_USE3", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_STILL_THRESH", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR_CAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TRIM_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC_BODYFIX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS1_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS1_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS1_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_POS3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR2_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR3_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3_ID", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_FAST_SAMPLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ENABLE_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYRO_RATE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC1_CALTEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR1_CALTEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC2_CALTEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR2_CALTEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_ACC3_CALTEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_GYR3_CALTEMP", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_FREQ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_BW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_ATT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_HMNCS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_REF", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_MODE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_HNTCH_OPTS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_LOG_BAT_CNT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_LOG_BAT_MASK", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_LOG_BAT_OPT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_LOG_BAT_LGIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_LOG_BAT_LGCT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_NOTCH_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_NOTCH_ATT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_NOTCH_FREQ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_NOTCH_BW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_TMIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_TMAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC1_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC1_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC1_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_ACC3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR1_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR1_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR1_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR2_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR2_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR2_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR3_X", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR3_Y", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("INS_TCAL1_GYR3_Z", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_SLOPE_RCALC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_ABORT_DEG", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_PITCH_CD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_FLARE_ALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_FLARE_SEC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_PF_ALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_PF_SEC", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_PF_ARSPD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_THR_SLEW", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DISARMDELAY", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_THEN_NEUTRL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_ABORT_THR", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_FLAP_PERCNT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_TYPE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_V_FWD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_SLOPE_A", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_SLOPE_B", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_APP_EXT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_V_DWN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_SLEW_SPD", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_ELEV_PWM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_ARSP_MAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_ARSP_MIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_L1", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_L1_I", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_YAW_LIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_L1_TCON", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_P", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_I", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_D", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_IMAX", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_ABORTALT", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("LAND_DS_AIL_SCL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MIS_TOTAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MIS_RESTART", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("MIS_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RALLY_TOTAL", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RALLY_LIMIT_KM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RALLY_INCL_HOME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC_OVERRIDE_TIME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC_PROTOCOLS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC0_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC0_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC0_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC0_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC0_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC0_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC1_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC1_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC1_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC1_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC1_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC1_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC2_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC2_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC2_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC2_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC2_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC2_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC3_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC3_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC3_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC3_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC3_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC3_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC4_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC4_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC4_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC4_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC4_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC4_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC5_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC5_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC5_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC5_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC5_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC5_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC6_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC6_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC6_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC6_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC6_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC6_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC7_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC7_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC7_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC7_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC7_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC7_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC8_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC8_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC8_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC8_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC8_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC8_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC9_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC9_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC9_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC9_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC9_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC9_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC10_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC10_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC10_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC10_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC10_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC10_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC11_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC11_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC11_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC11_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC11_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC11_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC12_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC12_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC12_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC12_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC12_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC12_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC13_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC13_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC13_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC13_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC13_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC13_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC14_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC14_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC14_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC14_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC14_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC14_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC15_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC15_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC15_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC15_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC15_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC15_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC16_MIN", 1000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC16_DZ", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC16_MAX", 2000f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC16_TRIM", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC16_REVERSED", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("RC16_OPTION", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("STAT_FLTTIME", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TERRAIN_ENABLE", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TERRAIN_SPACING", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TERRAIN_OPTIONS", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetParameter("TERRAIN_MARGIN", 0f, MAVLink.MAV_PARAM_TYPE.UINT8);
                    SetDefault(saveFile,defaultFile);
                }
            }
        }
    }
}